---
- name: Merge all .txt files into one .conf file
  hosts: localhost
  become: false
  gather_facts: false

  vars:
    wd: "/Users/kdor/Repos/ConcatenationStation"

  tasks:
    - name: Merge savedsearches together
      ansible.builtin.assemble:
        src: "{{ wd }}/savedsearches"
        dest: "{{ wd }}/savedsearches.conf"
        regexp: '\.txt$'
        delimiter: " "
        owner: kdor
        group: staff
        mode: '0644'

    - name: Merge macros together
      ansible.builtin.assemble:
        src: "{{ wd }}/macros"
        dest: "{{ wd }}/macros.conf"
        regexp: '\.txt$'
        delimiter: " "
        owner: kdor
        group: staff
        mode: '0644'
