name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
        image: splunk/splunk:latest
        options: --user root
    steps:
        - name: Checkout
        - uses: actions/checkout@v3
        - run: |
          mv $GITHUB_WORKSPACE/*.conf $SPLUNK_HOME/etc/system/local/.
          $SPLUNK_HOME/bin/splunk btool check