name: Test Configs

on:
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    container: 
        image: splunk/splunk:latest
        options: --user root
        
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        
        - name: Start Splunk
          run: $SPLUNK_HOME/bin/splunk start --accept-license --answer-yes --gen-and-print-passwd 

        - name: Move files
          run: mv $GITHUB_WORKSPACE/*.conf $SPLUNK_HOME/etc/system/local/.
        
        - name: Run btool check
          run: $SPLUNK_HOME/bin/splunk btool check